apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: type1
  name: nginx-deployment-type1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          # よくあるワークフロー
          resources:
            requests:
              cpu: "1"
            limits:
              memory: "256Mi"
              cpu: "2"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: type2
  name: nginx-deployment-type2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          # 不当にrequests吊り下げてlimitsでどうなるか様子見するパターン
          resources:
            requests:
              cpu: "0.25m"
            limits:
              memory: "256Mi"
              cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  namespace: type1
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  namespace: type2
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: type2 # 比較先NS強制的に付与
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
